In [1]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

In [2]:
arr1 = np.arange(9).reshape(3,3)

In [3]:
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [6]:
np.concatenate([arr1,arr1],axis=1)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

In [9]:
np.concatenate([arr1,arr1],axis=0)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [10]:
ser1 = Series([0,1,2],index=['T','U','V'])
ser2 = Series([3,4],index=['X','Y'])

In [11]:
ser1

T    0
U    1
V    2
dtype: int64

In [12]:
ser2

X    3
Y    4
dtype: int64

In [13]:
pd.concat([ser1,ser2])

T    0
U    1
V    2
X    3
Y    4
dtype: int64

In [14]:
pd.concat([ser1,ser2],axis=1)

0    1
T  0.0  NaN
U  1.0  NaN
V  2.0  NaN
X  NaN  3.0
Y  NaN  4.0

In [18]:
pd.concat([ser1,ser2],keys=['cat1','cat2'])

cat1  T    0
      U    1
      V    2
cat2  X    3
      Y    4
dtype: int64

In [19]:
# 키가 생긴당

In [20]:
dframe1 = DataFrame(np.random.randn(4,3),columns=['X','Y','Z'])
dframe2 = DataFrame(np.random.randn(3,3),columns=['Y','Q','X'])

In [21]:
dframe1

X         Y         Z
0 -1.499663 -1.089521 -0.175407
1 -0.588105 -0.149067 -0.376005
2  0.277915  0.714406 -1.938831
3 -0.259666 -1.832593  1.142053

In [22]:
dframe2

Y         Q         X
0 -1.046455 -1.860812 -0.309124
1  0.681539 -1.894748  1.884574
2 -1.469420 -2.136029 -0.835075

In [23]:
pd.concat([dframe1,dframe2])

Q         X         Y         Z
0       NaN -1.499663 -1.089521 -0.175407
1       NaN -0.588105 -0.149067 -0.376005
2       NaN  0.277915  0.714406 -1.938831
3       NaN -0.259666 -1.832593  1.142053
0 -1.860812 -0.309124 -1.046455       NaN
1 -1.894748  1.884574  0.681539       NaN
2 -2.136029 -0.835075 -1.469420       NaN

In [24]:
# 최대 확장된 상태로 합쳐지넹

In [25]:
pd.concat([dframe1,dframe2],ignore_index=True)

Q         X         Y         Z
0       NaN -1.499663 -1.089521 -0.175407
1       NaN -0.588105 -0.149067 -0.376005
2       NaN  0.277915  0.714406 -1.938831
3       NaN -0.259666 -1.832593  1.142053
4 -1.860812 -0.309124 -1.046455       NaN
5 -1.894748  1.884574  0.681539       NaN
6 -2.136029 -0.835075 -1.469420       NaN

In [ ]:
# 이그놀 언더스코어 인덱스는 붙이는 것과 안 붙이는 것이 어떤 차이가 있찌??

In [ ]:
url = 'http://pandas.pydata.org/pandas-docs/dev/generated/pandas.tools.merge.concat.html'