In [1]:
import numpy as np

In [2]:
arr = np.arange(11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ,
        3.16227766])

In [5]:
np.exp(arr)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03,   2.20264658e+04])

In [6]:
A = np.random.randn(10)

In [7]:
A


array([-0.15782325,  0.82361714, -0.62808572, -2.57831661,  0.25152295,
       -0.57919076, -0.09979452,  0.82021453,  0.45375929, -0.03155883])

In [8]:
B = np.random.randn(10)

In [9]:
B

array([-1.83133095,  1.27599693,  1.79620619,  0.85437837,  0.69511158,
       -1.48644432, -0.16592014, -1.26301752, -1.23567041, -1.01214402])

In [10]:
# Binary Functions
np.add(A,B)

array([-1.9891542 ,  2.09961407,  1.16812047, -1.72393824,  0.94663453,
       -2.06563507, -0.26571465, -0.44280299, -0.78191112, -1.04370284])

In [11]:
np.maximum(A,B)

array([-0.15782325,  1.27599693,  1.79620619,  0.85437837,  0.69511158,
       -0.57919076, -0.09979452,  0.82021453,  0.45375929, -0.03155883])

In [12]:
# 에이랑 비 비교해서 큰놈을 배열에 저장한다

In [ ]:
# Website 주소를 모르겠다... doc이였음